version: "3.8"

services:
  webkorps:
    container_name: webkorps-dev
    image: harrssh08/watchtower:nightly3
    volumes:
      #- ./data:/app/data
      - ../server:/app/server
      - ../db:/app/db
    ports:
      - "3001:3001" # <Host Port>:<Container Port>
      - "3307:3306"
